apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  nfs:
    path: /EDCOP/shared
    server: edcop-master.local
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Available
