apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: netdiag-deployment
spec:
  selector:
    matchLabels:
      app: netdiag-deployment
  replicas: 2 
  template:
    metadata:
      annotations:
        networks: '[  
        { "name": "calico" },
        { "name": "ovs-plugin" }
        ]'
      labels:
        app: netdiag-deployment
    spec:
      containers:
      - name: netdiag-deployment
        image: "scality/netdiag"
        command: ["top"]
        stdin: true
        tty: true

